services:
  changedetection:
    container_name: changedetection
    restart: unless-stopped
    image: lscr.io/linuxserver/changedetection.io:latest
    networks:
      - reverseproxy-nw
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - data:/config
    labels:
      - "Backup=Changedetection" # Sets the DVBM Backup Job Label
      - "AppPort=5000" # Sets the Application Port for the Reverse Proxy Job

networks:
  reverseproxy-nw: # Use the existing Reverse Proxy Network
    external: true

volumes:
  data:
