services:
  excalidraw:
    container_name: excalidraw
    restart: unless-stopped
    image: docker.io/excalidraw/excalidraw:latest
    networks:
      - reverseproxy-nw
    labels:
      - "AppPort=80" # Sets the Application Port for the Reverse Proxy Job
      - "Kuma.Name=Excalidraw" # Uptime Kuma monitor, created by the Uptime Kuma GitOps job

networks:
  reverseproxy-nw: # Use the existing Reverse Proxy Network
    external: true
