---
- name: Manage Plex servers
  hosts: plex
  become: true
  tasks:

    - name: Stop plexmediaserver service
      ansible.builtin.service:
        name: plexmediaserver
        state: stopped

    - name: Disable plexmediaserver service
      ansible.builtin.systemd:
        name: plexmediaserver
        enabled: no

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Check if reboot is required (Debian-based)
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
      when: ansible_facts['os_family'] == "Debian"
      become: true

    - name: Reboot the server if required (Debian-based)
      reboot:
        msg: "Reboot initiated by Ansible because updates were installed."
        test_command: whoami
      when:
        - ansible_facts['os_family'] == "Debian"
        - reboot_required_file.stat.exists
      become: true

    - name: Re-enable Plex service
      become: true
      ansible.builtin.systemd:
        name: plexmediaserver
        enabled: yes

    - name: Restart Plex service
      become: true
      ansible.builtin.systemd:
        name: plexmediaserver
        state: restarted
