services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    image: corentinth/it-tools:latest
    networks:
      - reverseproxy-nw
    labels:
      - "AppPort=80" # Sets the Application Port for the Reverse Proxy Job
      - "Kuma.Name=IT-Tools" # Uptime Kuma monitor, created by the Uptime Kuma GitOps job

networks:
  reverseproxy-nw: # Use the existing Reverse Proxy Network
    external: true
